### ISSUE TITLE
Horizontal movement impossible in TI-83 Premium CE

### ISSUE THREAD

**Issue by zh-tianyi** [EverydayCodeNet/AGARIO-CE#2]
Just installed, I have no idea why or how, please help.
Thanks
Here's a video showing the issue: https://drive.google.com/file/d/1Eq1nTQz7NxaAZwRsI7fmFIjZxxB3pqrU/view?usp=drivesdk

**Comment by EverydayCodeNet** [comment]
I have received a lot of complaints about the movement system. Here's how it works now:

[^]/[v] arrows take you straight up or straight down, but the left and right keys turn you to the left or right ~27.5 degrees. I could probably add a delay in between presses or add intermediate turning, which would allow for direct horizontal movement. Right now, slowly pressing the left and right keys is the only way to fix this issue!
